name: Create Release
on:
  push:
    tags:
      - v*
jobs:
  build-win:
    name: Build for Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
    - name: Install dependencies
      run: |
        msys2 -c 'pacman -S --noconfirm base-devel gcc mingw-w64-i686-toolchain mingw-w64-x86_64-cmake'
    - name: Create Build Directory
      run: |
        mkdir -p build/mingw64
    - name: Configure CMake
      shell: msys2 {0}
      run: |
        cmake -G "MinGW Makefiles" ../.. -DBUILD_SHARED_LIBS=ON -DFLATCC_OFFSET_SIZE=8 -DCMAKE_BUILD_TYPE=Release
      working-directory: ${{github.workspace}}/build/mingw64
    - name: Build flatcc_cli
      shell: msys2 {0}
      run: |
        cmake --build . --target flatcc_cli --config Release
      working-directory: ${{github.workspace}}/build/mingw64
    - name: Build flatccrt
      shell: msys2 {0}
      run: |
        cmake --build . --target flatccrt --config Release
      working-directory: ${{github.workspace}}/build/mingw64
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: flatcc-win64
        path: |
          bin/*.*
